name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: 
      - dev
      - future
      - feature/codecoverage-ci
    tags:
      - v[0-9]+.[0-9]+.[0-9]+ # Matches all semantic versioning tags with major, minor, patch
  pull_request:
    branches: 
      - dev
      - future

env:
  MORYX_OPTIMIZE_CODE: "false"
  MORYX_BUILD_CONFIG: "Release"
  MORYX_BUILDNUMBER: ${{github.run_number}}
  dotnet_sdk_version: '7.x'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  Build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet_sdk_version }}

      - name: Build
        shell: pwsh
        run: ./Build.ps1 -Build -Pack

      - name: Upload package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: artifacts/Packages/
          retention-days: 1


  UnitTests:
    needs: [Build]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK standard (7)
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet_sdk_version }}

      - name: Setup .NET SDK 6 for testing purposes
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
          
      # - name: Execute dotnet info
      #   run: dotnet --info

      - name: Execute dotnet restore
        run: dotnet restore

      - name: Execute dotnet build
        run: dotnet build

      - name: Execute dotnet test (needs coverlet.collector nuget)
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: moryx-core-test-results
          path: src\Tests\**\TestResults\**\coverage.cobertura.xml
          retention-days: 1

  IntegrationTests:
    needs: [Build]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet_sdk_version }}

      - name: Execute Integration Tests
        shell: pwsh
        run: ./Build.ps1 -IntegrationTests

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: moryx-core-test-results
          path: artifacts/Tests/
          retention-days: 1

  ReportGenerator:
    needs: [UnitTests, IntegrationTests]
    runs-on: windows-2019
    steps:
      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: moryx-core-test-results
          path: artifacts/moryx-core-test-results
          
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts/moryx-core-test-results
          
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.12
        with:
          reports: artifacts/test-results/**/TestResults\**\coverage.cobertura.xml; artifacts/moryx-core-test-results/*.Cobertura.xml
          targetdir: Coverage
          reporttypes: Html
          
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: moryx-core-coverage-results
          path: Coverage/
          retention-days: 1
          
          
  Release-Website:
    needs: [ReportGenerator]
    runs-on: ubuntu-latest
    steps:        
      - name: Download coverage results
        uses: actions/download-artifact@v2
        with:
          name: moryx-core-coverage-results
          path: artifacts/coverage-results

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync artifacts/coverage-results s3://moryx-code-coverage/moryx-core --delete



  Documentation:
    needs: [Build]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Generate docFx
        shell: pwsh
        run: ./Build.ps1 -GenerateDocs

      - name: Upload documentation results
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: artifacts/Documentation/
          retention-days: 1

  Publish:
    needs: [Build, UnitTests]
    if: ${{ github.event_name == 'push' }}
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet_sdk_version }}
  
      - name: Download package artifacts
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: artifacts/Packages/

      - name: Publish on MyGet-CI
        if: ${{ github.ref == 'refs/heads/dev' }} # dev branche is published to myget moryx
        shell: pwsh
        env:
          MORYX_NUGET_APIKEY: ${{secrets.MYGET_TOKEN}}
          MORYX_PACKAGE_TARGET: "https://www.myget.org/F/moryx/api/v2/package"
          MORYX_PACKAGE_TARGET_V3: "https://www.myget.org/F/moryx/api/v3/index.json"
        run: ./Build.ps1 -Publish

      - name: Publish on MyGet-Future
        if: ${{ github.ref == 'refs/heads/future' }} # Future branch is published to myget moryx-future
        shell: pwsh
        env:
          MORYX_NUGET_APIKEY: ${{secrets.MYGET_TOKEN}}
          MORYX_PACKAGE_TARGET: "https://www.myget.org/F/moryx-future/api/v2/package"
          MORYX_PACKAGE_TARGET_V3: "https://www.myget.org/F/moryx-future/api/v3/index.json"
        run: ./Build.ps1 -Publish

      - name: Publish on NuGet
        if: ${{ startsWith(github.ref, 'refs/tags/v') }} # Version Tags are published to nuget
        shell: pwsh
        env:
          MORYX_NUGET_APIKEY: ${{secrets.NUGET_TOKEN}}
          MORYX_PACKAGE_TARGET: "https://api.nuget.org/v3/index.json"
          MORYX_PACKAGE_TARGET_V3: "https://api.nuget.org/v3/index.json"
        run: ./Build.ps1 -Publish
